#pragma once


#include "./calculation/ce_inasan_o1.h"
#include "./calculation/ce_regemorter.h"
#include "./calculation/ci_arnaud_younger.h"
#include "./calculation/cti_arnaud.h"
#include "./calculation/ctr_arnaud.h"
#include "./calculation/dr_badnell.h"
#include "./calculation/lte.h"
#include "./calculation/nlte.h"
#include "./calculation/pe_tasitsiomi.h"
#include "./calculation/pi_tasitsiomi.h"
#include "./calculation/rbb_doppler_inasan_o1.h"
#include "./calculation/rbb_voigt_inasan_o1.h"
#include "./calculation/rbf_inasan_o1.h"
#include "./calculation/rr_badnell_verner.h"
#include "./calculation/rr_seaton.h"
#include "./calculation/se_nist_o1.h"
#include "./data/element.h"
#include "./data/sun_gueymard.h"
#include "./data/o1_inasan.h"